server:
  port: 8081  # Port for User Service

spring:
  profiles:
    active: default  # Default profile is active

  datasource:
    username: postgres
    password: Ab123456
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false  # Disable open-in-view to avoid potential performance issues

  rabbitmq:
    username: guest
    password: guest

# Custom application-specific settings
app:
  wallet-creation: walletCreationQueue

# Logging level for the User Service
logging:
  level:
    com.jack.userservice: INFO

  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
# SpringDoc settings for API documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

# Default profile (local development and testing)
---
spring:
  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb  # Dedicated database for User Service

  rabbitmq:
    host: localhost
    port: 5672

# Docker profile (for running in containers)
---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://db:5432/userdb  # Database connection for Docker environment

  rabbitmq:
    host: rabbitmq  # RabbitMQ host in Docker (referring to service name)
    port: 5672
