spring:
  rabbitmq:
    host: localhost  # Local RabbitMQ
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb  # Local database connection
    username: postgres
    password: Ab123456
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false  # Disable open-in-view for better performance

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      password: Ab123456
      timeout: 60000

# Custom application-specific settings
app:
  wallet:
    cache-prefix: "walletBalance:"  # Redis key prefix for wallet balances
    reply-to-queue: user-service.response.queue  # Reply queue for responses
    queue:
      create: wallet.create.queue      # Queue for wallet creation messages
      balance: wallet.balance.queue    # Queue for wallet balance requests
    exchange: wallet-exchange          # Exchange for wallet messages
    routing-key:
      create: wallet.creation          # Routing key for wallet creation
      balance: wallet.balance          # Routing key for wallet balance requests

# SpringDoc settings for API documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

# Logging pattern
logging:
  level:
    com.jack.userservice: INFO

  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"


